"""add_ai_pricing_entitlements_system

Revision ID: 242cb3b44166
Revises: fe02658535a0
Create Date: 2026-08-21 11:26:18.541157
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242cb3b44166'
down_revision: Union[str, None] = 'fe02658535a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_configs_key'), 'admin_configs', ['key'], unique=True)
    op.create_table('ai_usage_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('credit_charged', sa.Integer(), nullable=False),
    sa.Column('credit_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_chat_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_transaction_id'], ['ai_credit_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['ai_chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_records_request_id'), 'ai_usage_records', ['request_id'], unique=False)
    op.add_column('ai_credit_transactions', sa.Column('amount', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('ai_credit_transactions', sa.Column('credit_type', sa.String(length=50), nullable=False, server_default='monthly_included'))
    op.add_column('ai_credit_transactions', sa.Column('transaction_type', sa.String(length=50), nullable=False, server_default='consume'))
    op.add_column('ai_credit_transactions', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('ai_credit_transactions', sa.Column('reference_id', sa.String(length=100), nullable=True))
    op.alter_column('ai_credit_transactions', 'ad_account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ai_credit_transactions', 'gemini_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('users', sa.Column('trial_credits_remaining', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('monthly_credits_remaining', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('purchased_credits_remaining', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('admin_assigned_optimization_slots', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_credits_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_credits_reset_at')
    op.drop_column('users', 'admin_assigned_optimization_slots')
    op.drop_column('users', 'purchased_credits_remaining')
    op.drop_column('users', 'monthly_credits_remaining')
    op.drop_column('users', 'trial_credits_remaining')
    op.alter_column('ai_credit_transactions', 'gemini_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ai_credit_transactions', 'ad_account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ai_credit_transactions', 'reference_id')
    op.drop_column('ai_credit_transactions', 'description')
    op.drop_column('ai_credit_transactions', 'transaction_type')
    op.drop_column('ai_credit_transactions', 'credit_type')
    op.drop_column('ai_credit_transactions', 'amount')
    op.drop_index(op.f('ix_ai_usage_records_request_id'), table_name='ai_usage_records')
    op.drop_table('ai_usage_records')
    op.drop_index(op.f('ix_admin_configs_key'), table_name='admin_configs')
    op.drop_table('admin_configs')
    # ### end Alembic commands ###
