"""add_performance_goal_fields_to_adsets

Revision ID: 27c33476554d
Revises: f23f651aadce
Create Date: 2026-08-19 12:40:47.495014
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c33476554d'
down_revision: Union[str, None] = 'f23f651aadce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_sets', sa.Column('motive', sa.String(length=100), nullable=True))
    op.add_column('ad_sets', sa.Column('performance_goal', sa.String(length=100), nullable=True))
    op.add_column('ad_sets', sa.Column('optimization_event', sa.String(length=100), nullable=True))
    op.add_column('ad_sets', sa.Column('performance_goal_profile_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_ad_sets_performance_goal'), 'ad_sets', ['performance_goal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_sets_performance_goal'), table_name='ad_sets')
    op.drop_column('ad_sets', 'performance_goal_profile_id')
    op.drop_column('ad_sets', 'optimization_event')
    op.drop_column('ad_sets', 'performance_goal')
    op.drop_column('ad_sets', 'motive')
    # ### end Alembic commands ###
