"""add_briefs_and_update_recommendations

Revision ID: 2d205ecfe3d2
Revises: e29a7c7e129d
Create Date: 2026-08-19 11:01:59.324059
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d205ecfe3d2'
down_revision: Union[str, None] = 'e29a7c7e129d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_memories',
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('pattern_key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('supporting_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('date_range', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_daily_briefs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('results', sa.Integer(), nullable=False),
    sa.Column('primary_kpi', sa.String(length=50), nullable=False),
    sa.Column('primary_kpi_value', sa.Float(), nullable=False),
    sa.Column('primary_kpi_change', sa.Float(), nullable=False),
    sa.Column('biggest_win', sa.JSON(), nullable=True),
    sa.Column('biggest_problem', sa.JSON(), nullable=True),
    sa.Column('positive_changes', sa.JSON(), nullable=True),
    sa.Column('negative_changes', sa.JSON(), nullable=True),
    sa.Column('watch_items', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('experiments', sa.JSON(), nullable=True),
    sa.Column('dont_change_items', sa.JSON(), nullable=True),
    sa.Column('top_priorities', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_weekly_briefs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('results', sa.Integer(), nullable=False),
    sa.Column('primary_kpi', sa.String(length=50), nullable=False),
    sa.Column('primary_kpi_value', sa.Float(), nullable=False),
    sa.Column('primary_kpi_change', sa.Float(), nullable=False),
    sa.Column('biggest_win', sa.JSON(), nullable=True),
    sa.Column('biggest_problem', sa.JSON(), nullable=True),
    sa.Column('winning_pattern', sa.JSON(), nullable=True),
    sa.Column('creative_fatigue_items', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('dont_change_items', sa.JSON(), nullable=True),
    sa.Column('experiments', sa.JSON(), nullable=True),
    sa.Column('top_priorities', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_experiments',
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('control_entity_id', sa.Uuid(), nullable=False),
    sa.Column('variant_entity_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis', sa.String(length=1000), nullable=False),
    sa.Column('primary_metric', sa.String(length=50), nullable=False),
    sa.Column('secondary_metrics', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('results_summary', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_recommendations', sa.Column('objective', sa.String(length=50), nullable=True))
    op.add_column('ai_recommendations', sa.Column('problem', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('expected_impact', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('adset_id', sa.Uuid(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('ad_id', sa.Uuid(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('creative_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_recommendations', 'creative_id')
    op.drop_column('ai_recommendations', 'ad_id')
    op.drop_column('ai_recommendations', 'adset_id')
    op.drop_column('ai_recommendations', 'campaign_id')
    op.drop_column('ai_recommendations', 'expected_impact')
    op.drop_column('ai_recommendations', 'evidence')
    op.drop_column('ai_recommendations', 'root_cause')
    op.drop_column('ai_recommendations', 'problem')
    op.drop_column('ai_recommendations', 'objective')
    op.drop_table('ad_experiments')
    op.drop_table('ai_weekly_briefs')
    op.drop_table('ai_daily_briefs')
    op.drop_table('account_memories')
    # ### end Alembic commands ###
