"""add ads service models and user fields

Revision ID: 973d81190f14
Revises: a1b2c3d4e5f6
Create Date: 2026-08-23 23:39:21.638816
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973d81190f14'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_ad_service_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('business_location', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('industry_other', sa.String(length=255), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('advertised_product', sa.String(length=255), nullable=False),
    sa.Column('campaign_objective', sa.String(length=100), nullable=False),
    sa.Column('daily_budget', sa.String(length=100), nullable=False),
    sa.Column('number_of_ads', sa.Integer(), nullable=False),
    sa.Column('creative_required', sa.Boolean(), nullable=False),
    sa.Column('additional_services', sa.JSON(), nullable=False),
    sa.Column('meta_account_exists', sa.Boolean(), nullable=False),
    sa.Column('meta_business_id', sa.String(length=128), nullable=True),
    sa.Column('meta_ad_account_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('partner_access_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_packs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service_request_id', sa.Uuid(), nullable=True),
    sa.Column('pack_type', sa.String(length=100), nullable=False),
    sa.Column('total_ad_credits', sa.Integer(), nullable=False),
    sa.Column('used_ad_credits', sa.Integer(), nullable=False),
    sa.Column('remaining_ad_credits', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('non_refundable_terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('non_refundable_terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['meta_ad_service_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_quotations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service_request_id', sa.Uuid(), nullable=False),
    sa.Column('regular_total', sa.Integer(), nullable=False),
    sa.Column('discount_total', sa.Integer(), nullable=False),
    sa.Column('final_total', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['meta_ad_service_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('ads_service_eligible', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('users', sa.Column('restriction_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('intro_offer_eligible', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('intro_offer_used', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('intro_offer_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('intro_offer_service_request_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'intro_offer_service_request_id')
    op.drop_column('users', 'intro_offer_used_at')
    op.drop_column('users', 'intro_offer_used')
    op.drop_column('users', 'intro_offer_eligible')
    op.drop_column('users', 'restriction_reason')
    op.drop_column('users', 'ads_service_eligible')
    op.drop_table('service_quotations')
    op.drop_table('ad_packs')
    op.drop_table('meta_ad_service_requests')
    # ### end Alembic commands ###
