"""add_campaign_plan_id_to_service_request

Revision ID: 99914befe463
Revises: d2b5b26d3932
Create Date: 2026-08-24 19:32:39.129779
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99914befe463'
down_revision: Union[str, None] = 'd2b5b26d3932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_ad_service_requests', sa.Column('campaign_plan_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'meta_ad_service_requests', 'campaign_plans', ['campaign_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meta_ad_service_requests', type_='foreignkey')
    op.drop_column('meta_ad_service_requests', 'campaign_plan_id')
    # ### end Alembic commands ###
