"""add_order_statuses_to_ad_packs

Revision ID: 9dc2f3fa02c7
Revises: 973d81190f14
Create Date: 2026-08-24 17:33:12.974899
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc2f3fa02c7'
down_revision: Union[str, None] = '973d81190f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_packs', sa.Column('order_statuses', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_packs', 'order_statuses')
    # ### end Alembic commands ###
