"""add_email_template_configs

Revision ID: bbe4f7d67202
Revises: a8fb1bcaeca0
Create Date: 2026-08-28 13:35:13.140362
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe4f7d67202'
down_revision: Union[str, None] = 'a8fb1bcaeca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template_configs',
    sa.Column('trigger_key', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_key')
    )
    op.add_column('team_members', sa.Column('allowed_tabs', sa.String(length=1000), nullable=True))
    op.add_column('team_members', sa.Column('allowed_ad_accounts', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'allowed_ad_accounts')
    op.drop_column('team_members', 'allowed_tabs')
    op.drop_table('email_template_configs')
    # ### end Alembic commands ###
