"""add_razorpay_order_id_to_service_quotations

Revision ID: c3a9f1b2d4e6
Revises: bbe4f7d67202
Create Date: 2026-09-01 16:45:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a9f1b2d4e6'
down_revision: Union[str, None] = 'bbe4f7d67202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_quotations', sa.Column('razorpay_order_id', sa.String(128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_quotations', 'razorpay_order_id')
    # ### end Alembic commands ###
