"""add_deletion_scheduled_at_to_user

Revision ID: d01fb2224353
Revises: 379b387b0311
Create Date: 2026-08-18 17:42:02.596686
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01fb2224353'
down_revision: Union[str, None] = '379b387b0311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletion_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_scheduled_at')
    # ### end Alembic commands ###
