"""add_trial_columns_to_user

Revision ID: e29a7c7e129d
Revises: fce6834bb84e
Create Date: 2026-08-18 18:56:57.242437
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29a7c7e129d'
down_revision: Union[str, None] = 'fce6834bb84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('trial_used', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('trial_meta_account_id', sa.String(length=128), nullable=True))
    
    # Pre-populate defaults for existing users
    op.execute("UPDATE users SET trial_status = 'not_started' WHERE trial_status IS NULL")
    op.execute("UPDATE users SET trial_used = FALSE WHERE trial_used IS NULL")
    
    # Alter columns to be NOT NULL
    op.alter_column('users', 'trial_status', nullable=False)
    op.alter_column('users', 'trial_used', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_meta_account_id')
    op.drop_column('users', 'trial_used')
    op.drop_column('users', 'trial_status')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'trial_started_at')
    # ### end Alembic commands ###
