"""add_ml_feature_store_and_optimization_actions

Revision ID: f23f651aadce
Revises: 2d205ecfe3d2
Create Date: 2026-08-19 11:11:52.256546
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23f651aadce'
down_revision: Union[str, None] = '2d205ecfe3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_feature_store',
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('ad_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('feature_date', sa.Date(), nullable=False),
    sa.Column('creative_type', sa.String(length=50), nullable=True),
    sa.Column('creative_length', sa.Integer(), nullable=True),
    sa.Column('headline_length', sa.Integer(), nullable=True),
    sa.Column('primary_text_length', sa.Integer(), nullable=True),
    sa.Column('hook_type', sa.String(length=50), nullable=True),
    sa.Column('has_offer', sa.Boolean(), nullable=True),
    sa.Column('has_price', sa.Boolean(), nullable=True),
    sa.Column('has_social_proof', sa.Boolean(), nullable=True),
    sa.Column('cta_type', sa.String(length=100), nullable=True),
    sa.Column('placement', sa.String(length=100), nullable=True),
    sa.Column('audience_type', sa.String(length=100), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('spend', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('cpl', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('outcome_label', sa.String(length=50), nullable=True),
    sa.Column('extra_features', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'feature_date', name='uq_ml_feature_ad_date')
    )
    op.create_table('optimization_actions',
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('executed_at', sa.String(length=50), nullable=True),
    sa.Column('rolled_back_at', sa.String(length=50), nullable=True),
    sa.Column('pre_action_metrics', sa.JSON(), nullable=True),
    sa.Column('post_action_metrics', sa.JSON(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('learning_outcome', sa.Text(), nullable=True),
    sa.Column('learning_committed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ai_recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_actions')
    op.drop_table('ml_feature_store')
    # ### end Alembic commands ###
