"""add_industry_to_meta_ad_account

Revision ID: fce6834bb84e
Revises: d01fb2224353
Create Date: 2026-08-18 18:30:17.858878
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce6834bb84e'
down_revision: Union[str, None] = 'd01fb2224353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_ad_accounts', sa.Column('industry', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_ad_accounts', 'industry')
    # ### end Alembic commands ###
