"""add_ai_optimization_feature

Revision ID: ffde86fa1798
Revises: 27c33476554d
Create Date: 2026-08-21 08:28:30.033840
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffde86fa1798'
down_revision: Union[str, None] = '27c33476554d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clean up orphan rows to avoid foreign key violations
    op.execute("DELETE FROM account_memories WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")
    op.execute("DELETE FROM ad_experiments WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")
    op.execute("DELETE FROM ai_daily_briefs WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")
    op.execute("DELETE FROM ai_weekly_briefs WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")
    op.execute("DELETE FROM campaigns WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")
    op.execute("DELETE FROM ml_feature_store WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")
    op.execute("DELETE FROM optimization_actions WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")
    op.execute("DELETE FROM ai_recommendations WHERE ad_account_id NOT IN (SELECT id FROM meta_ad_accounts);")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_optimization_configs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('business_objective', sa.String(length=255), nullable=True),
    sa.Column('primary_kpi', sa.String(length=100), nullable=True),
    sa.Column('secondary_kpi', sa.String(length=100), nullable=True),
    sa.Column('target_cpl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('target_cpa', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('target_roas', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_analysis_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memory', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_optimization_configs_campaign_id'), 'ai_optimization_configs', ['campaign_id'], unique=True)
    op.create_table('ai_optimization_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ad_account_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('context_version', sa.String(length=20), nullable=False),
    sa.Column('gemini_model', sa.String(length=100), nullable=False),
    sa.Column('recommendations_generated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['meta_ad_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'account_memories', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ad_experiments', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_daily_briefs', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    op.add_column('ai_recommendations', sa.Column('fingerprint', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'ai_recommendations', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_weekly_briefs', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'campaigns', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ml_feature_store', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'optimization_actions', 'meta_ad_accounts', ['ad_account_id'], ['id'], ondelete='CASCADE')
    # Enable Row Level Security (RLS)
    op.execute("ALTER TABLE public.ai_optimization_configs ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.ai_optimization_logs ENABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'optimization_actions', type_='foreignkey')
    op.drop_constraint(None, 'ml_feature_store', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'ai_weekly_briefs', type_='foreignkey')
    op.drop_constraint(None, 'ai_recommendations', type_='foreignkey')
    op.drop_column('ai_recommendations', 'fingerprint')
    op.drop_constraint(None, 'ai_daily_briefs', type_='foreignkey')
    op.drop_constraint(None, 'ad_experiments', type_='foreignkey')
    op.drop_constraint(None, 'account_memories', type_='foreignkey')
    op.drop_table('ai_optimization_logs')
    op.drop_index(op.f('ix_ai_optimization_configs_campaign_id'), table_name='ai_optimization_configs')
    op.drop_table('ai_optimization_configs')
    # Disable Row Level Security (RLS)
    op.execute("ALTER TABLE public.ai_optimization_configs DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.ai_optimization_logs DISABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###
